# Generated by Django 5.1.6 on 2025-03-02 15:31

import django.core.validators
import django.db.models.deletion
import gameapi.constants
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MultiplayerGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_1_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("player_2_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("waiting_another_player", models.BooleanField(default=True)),
                (
                    "player_1_choice",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "player_2_choice",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            (
                                gameapi.constants.Result["WIN"],
                                gameapi.constants.Result["WIN"],
                            ),
                            (
                                gameapi.constants.Result["LOSE"],
                                gameapi.constants.Result["LOSE"],
                            ),
                            (
                                gameapi.constants.Result["TIE"],
                                gameapi.constants.Result["TIE"],
                            ),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "player_1_choice",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "player_2_choice",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcomes",
                        to="gameapi.multiplayergame",
                    ),
                ),
            ],
        ),
    ]
